sudo: false
language: cpp
before_script: 
  - git submodule update --init --recursive
  - export CXX=`which g++-4.8`
  - export CC=`which gcc-4.8`
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-4.8
      - valgrind
      - cmake-data
      - cmake
script:
  - mkdir build
  - cd build
  - cmake -DMEMORY_CHECK=ON .. 
  - make
  - make test
 
